---
- name: Provision newly installed Debian based server
  hosts: remote
  become: yes
  become_user: root
  gather_facts: no
  roles:
    - common
    - user-group
    - user
    - dotfiles
    # - postgres96
    # - nginx
    # - redis
    # - docker
    # - docker-compose
    - disable-root-ssh
