---
- name: Add normal user
  user:
    name: "{{ username }}"
    shell: /bin/bash
    group: admin
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/my_key

- name: Add authorized keys
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_items: "{{ ssh_public_keys }}"
