- name: Add Postgresql96 Repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
  register: pg_repo

- name: Add Postgresql Repo apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  register: pg_repo_key
  when: pg_repo|success

- name: Install Postgresql96
  apt:
    name: postgresql-9.6
    state: installed
    update_cache: true
  when: pg_repo_key | success
