---
- name: Gather facts
  setup:

- name: Set IPv4 as the precedence over IPv6
  lineinfile:
    path: /etc/gai.conf
    state: present
    line: "precedence ::ffff:0:0/96 100"

- name: Install aptitude
  apt:
    name: aptitude
    state: installed
    update_cache: true

- name: Perform safe upgrade
  apt:
    upgrade: safe
    update_cache: true

- include_tasks: tools.yml
