---
- name: Install Tools
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: true
  with_items:
    - build-essential
    - curl
    - git
    - vim
    - htop
    - libpq-dev
    - libssl-dev
    - zlib1g-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - libffi-dev

- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - python-dev
    - python-setuptools

- name: Install Python pip
  easy_install:
    name: pip
