---
- name: Add latest Vim repository
  apt_repository:
    repo: ppa:jonathonf/vim
    state: present

- name: Add Thoughtbot RCM repository
  apt_repository:
    repo: "deb http://apt.thoughtbot.com/debian/ stable main"

- name: Add Thoughtbot RCM repository key
  apt_key:
    url: https://apt.thoughtbot.com/thoughtbot.gpg.key

- name: Install Tools
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: true
  with_items:
    - build-essential
    - python2.7
    - curl
    - git
    - vim
    - htop
    - libpq-dev
    - libssl-dev
    - zlib1g-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - libffi-dev
    - rcm

- name: Set Python 2.7 as default
  raw: update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - python-dev
    - python-setuptools

- name: Install Python pip
  easy_install:
    name: pip

